flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: f9309bc46e4bf24b3a1d53663297851394a89a3f
  extra-dep: true
extra-deps:
- xml-conduit-1.5.0
- hslua-0.5.0
- skylighting-0.3.3
- texmath-0.9.4.1
- haddock-library-1.4.3
- hs-bibutils-5.5
- rfc5051-0.1.0.3
- Glob-0.7.14
resolver: nightly-2017-08-10
